

kind: pipeline
name: default


workspace:
  path: /drone/src
  
steps:
- name: create-test
  image: blazerunner/blazemeter:latest
  environment:   
    apikey:
      from_secret: apiKey
    apisecret:
      from_secret: apiSecret
    testid: 9562975
    continuepipeline: true


    
