

kind: pipeline
name: default


workspace:
  path: /drone/src
  
steps:
- name: run-test
  image: blazerunner/blazemeter
  environment:   
    apikey:
      from_secret: apiKey
    apisecret:
      from_secret: apiSecret
    testid: 9562975
    continuepipeline: true


    
