pipeline:
  steps:
- name: docker  
  image: poojamutadak/blazemeter
  settings:
    username: poojamutadak
    password: Advik@123
    repo: poojamutadak/blazemeter
    build_args:
      - apikey=673e0985b554e480881605e1
