kind: pipeline
name: default


workspace:
  path: /drone/src
  
steps:
- name: create-test
  image: blazerunner/blazemeter
  environment:   
    apikey:
      from_secret: apiKey
    apisecret:
      from_secret: apiSecret
    testname: Drone Pipeline Demo
    projectid: 881861
    createtest: true
    inputstartfile: BlazeDemoTest.jmx
    inputallfiles: /drone/src/Dependencies  
    uploadfilechk: true
