

kind: pipeline
name: default


workspace:
  path: /drone/src
  
steps:
- name: create-test
  image: poojamutadak/blazemeter
  environment:   
    apikey:
      from_secret: apiKey
    apisecret:
      from_secret: apiSecret
    testname: Drone Pipeline Demo  Pooja 4
    projectid: 881861
    createtest: true
    inputstartfile: BlazeDemoTest.jmx
    inputallfiles: /drone/src/Dependencies  
    Uploadfilechk: true
    totalusers: 1
    duration: 1
    rampup: 1
    ContinuePipeline: true

    
