kind: pipeline
type: docker
name: default

workspace:
  path: /home/blazemeter
  
platform:
  os: linux
  arch: amd64
  
  
steps:
- name: run-test
  pull: always
  build:
  image: poojamutadak/blazemeter
  commands:
   docker run -e apikey=673e0985b554e480881605e1
