# kind: pipeline
# type: docker
# name: default

# workspace:
  # path: /home/blazemeter
  
# platform:
  # os: linux
  # arch: amd64
  
  
# steps:
# - name: run-test
  # pull: always
  # build:
  # environment:
    # APIKEY:
      # from_secret: APIKEY   
  # image: poojamutadak/blazemeter 

kind: pipeline
name: default

#workspace:
#  path: /ImageTagDetection/AzureImageTagDetection/
# volumes:
# - name: cache
  # host: 
    # path: /
    

workspace:
  path: /drone/src
  
steps:
- name: create-test
  image: poojamutadak/blazemeter:6.2
  environment:    
    apikey: 673e0985b554e480881605e1
    apisecret: f4077e40595c183537225e9f30a8c08f311d2166bcedb4336be7e49854cc6540e4c159a2
    testname: Pooja Drone Dummy 
    projectid: 881861
    createtest: true
    inputstartfile: Dummy.jmx
    testurl: https://a.blazemeter.com/app/#/accounts/140171/workspaces/438644/projects/538695/tests/9092315/edit

    

  # APIKEY: my-cluster
  # APISECRET: my-cluster  
  # TESTURL: my-cluster  
