

kind: pipeline
name: default


workspace:
  path: /drone/src
  
steps:
- name: create-test
  image: poojamutadak/blazemeter:4.1
  environment:   
    apikey:
      from_secret: apiKey
    apisecret:
      from_secret: apiSecret
    testid: 9562975

    
