

kind: pipeline
name: default


workspace:
  path: /drone/src
  
steps:
- name: run-test
  image: poojamutadak/blazemeter
  environment:   
    apikey:
      from_secret: apiKey
    apisecret:
      from_secret: apiSecret
    createtest: false   
    testurl: https://a.blazemeter.com/app/#/accounts/140171/workspaces/133647/projects/881861/tests/9225544
    ContinuePipeline: false

    
