kind: pipeline
type: docker
name: default

workspace:
  path: /home/blazemeter
  
platform:
  os: linux
  arch: amd64
  
  
steps:
- name: run-test
  pull: always
  image: poojamutadak/blazemeter
   settings:
    username: kevinbacon
    password: pa55word
    repo: poojamutadak/blazemeter
    build_args:
      - apikey=673e0985b554e480881605e1
