
kind: pipeline
name: default


workspace:
  path: /drone/src
  
steps:
- name: create-test
  image: poojamutadak/blazemeter:7.0
  environment:    
    apikey: 673e0985b554e480881605e1
    apisecret: f4077e40595c183537225e9f30a8c08f311d2166bcedb4336be7e49854cc6540e4c159a2
    testname: Pooja Drone with Dependencies
    projectid: 881861
    createtest: false
    inputstartfile: BlazeDemoTest.jmx
    inputallfiles: /drone/src/Dependencies
    testurl: https://a.blazemeter.com/app/#/accounts/140171/workspaces/133647/projects/881861/tests/9225544
    Uploadfilechk: false
    
