

kind: pipeline
name: default


workspace:
  path: /drone/src
  
steps:
- name: create-test
  image: poojamutadak/blazemeter:5.0
  environment:   
    apikey:
      from_secret: apiKey
    apisecret:
      from_secret: apiSecret
    testid: 10166181
    continuepipeline: true
    multitests: true

    
