version: 2.1 # Use version 2.1 to enable orb usage.

orbs:
  win: circleci/windows@2.2.0 # The Windows orb give you everything you need to start using the Windows executor.
parameters:
  apikey:
    type: string
    default: "b9107809a101b8b788e9964f"
  apisecret:
    type: string
    default: "24da75ad1302cfb986fe84846288e3c9aecb61742a269f0927db60b286aedbf4f9c28df6"
  testurl:
    type: string
    default: "https://a.blazemeter.com/app/#/accounts/140171/workspaces/438644/projects/538695/tests/9092315/edit"
jobs:
  build: # name of your job
    executor:
      name: win/default # executor type
      size: "medium" # resource class, can be "medium", "large", "xlarge", "2xlarge", defaults to "medium" if not specified

    steps:
      # Commands are run in a Windows virtual machine environment
      - checkout
      - run: powershell -File build.ps1 -apikey << pipeline.parameters.apikey >>  -apisecret << pipeline.parameters.apisecret >>