 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/vs2019
      shell: powershell.exe
    environment:
      FOO: "bar"    
    steps:
      - checkout
      - run: Write-Host "Hello $TEST_VAR" # Prints "Hello "
      - run: Write-Host "Hello $FOO" # Prints "Hello "
